### ISSUE TITLE
Lab testing 

### ISSUE THREAD

**Issue by Shawn-1992** [Shawn-1992/Group-1-repo-projects#2]
@njgarner  Please download lab files and conduct user acceptance testing

**Comment by Shawn-1992** [comment]
@kristinamarkina, would it be possible for you to download the selenium  branch onto your local IDE? The repository should include a doc file with lab instructions along with every other file you should need to run through the lab. You could also make some unit tests to make sure what the lab is asking the user to do will actually work properly.

**Comment by Shawn-1992** [comment]
Just uploaded the CI/CD doc in the DevOps branch. Try running through the lab (Its pretty straight forward) and make sure there are no glaring errors. The professor also wants us testing the labs so writing some unit tests might be useful here.  The lab was modeled after the following Youtube video: https://www.youtube.com/watch?v=kezinXSoV5A, if you want a more in depth tutorial on topic, check it out!

**Comment by njgarner** [comment]
@Shawn-1992 I navigated through the CID lab and found it straightforward. There is plenty of information on CI/CD and the GitHub workflow. However, DevOps goes unexplored. It would be a good idea to address what DevOps is and how users are practicing DevOps via the lab. I am unsure what unit tests to implement, but I had no issues completing the lab.

**Comment by Shawn-1992** [comment]
@njgarner Glad to hear that the lab went smoothly. That is a good suggestion incorporate a DevOps section into the lab, I will work on adding that in this week. I also edited the youtubue link in my prior comment to point to the correct youtube vid.

**Comment by Shawn-1992** [comment]
I am currently working on writing some pytests for the Selenium lab

**Comment by kristinamarkina** [comment]
Selenium lab marked as  completed and tested
